export const INTAKE_SITE_STAGING = 'api.openobserve.ai'
export const INTAKE_SITE_US1 = 'api.openobserve.ai'
export const INTAKE_SITE_EU1 = 'api.openobserve.ai'
export const INTAKE_SITE_AP1 = 'api.openobserve.ai'
export const INTAKE_SITE_US1_FED = 'api.openobserve.ai'
